import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen flex justify-center items-center gap-12 bg-white`}>
      <div className="w-[1440px] h-screen flex mt-10">
        {children}
        <img className="w-[856px] h-[904px] rounded-4" src="pz.png"></img>
      </div>
    </div>
  );
}
