import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navi } from "./components/Navi";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      style={{ backgroundColor: "#F4F4F5" }}
      className={`flex flex-row w-screen h-fit min-h-screen justify-center gap-2 bg-[#f4f4f5cc]`}>
      <Navi />
      {children}
    </div>
  );
}
